baseURL: https://jacegem.github.io/log
languageCode: en-us
title: LPP
theme: 'PaperMod'

params:
  homeInfoParams:
    Title: Logseq Publish Pages 😎
    Content: “Talk is cheap. Show me the code.”

  socialIcons: # optional
    - name: 'github'
      url: 'https://github.com/jacegem'
    - name: 'email'
      url: 'mailto:jacegem@gmail.com'
    # - name: "youtube"
    #   url: "https://www.youtube.com/channel/XXX"
    # - name: 'twitter'
    # url: 'https://twitter.com/XXX'
    # - name: "kofi"
    #   url: "https://buymeacoffee.com/XXX"
    # - name: "rss"
    #   url: "https://XXX.github.io/index.xml"
  ShowReadingTime: true
  author: 'Jace'
  contact: 'jacegem@gmail.com'
  feedlinks: true
  copyright: '<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->'
  mobileMenu: true
  favicon: 'favicon.ico'
  icon: 'favicon.ico'
  image: 'unicorn.ico'

  # PaperMod page config
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  disableScrollToTop: false
  showtoc: true
  tocopen: true

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon.ico"
    favicon16x16: "favicon.ico"
    favicon32x32: "favicon.ico"
    apple_touch_icon: "favicon.ico"
    safari_pinned_tab: "favicon.ico"
  

  label:
    text: "Portal"
    icon: "unicorn72x72.png"
    iconHeight: 35

  #Google Analytics 4 optional
  env: #production
  GoogleAnalytics: 'G-00000XXXXX'
  sitemap:
    changefreq: daily
    filename: sitemap.xml
    priority: 0.5

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    # lineNos: true
    style: monokai
